### ISSUE TITLE
Version 0.2.0 does not exist

### ISSUE THREAD

**Issue by mnbayan** [KyleGoddard/KGFloatingDrawer#11]
Running `pod 'KGFloatingDrawer', '~> 0.2.0'` generates an error:

![screen shot 2015-10-16 at 9 16 34 pm](https://cloud.githubusercontent.com/assets/8461871/10542518/3d6902ec-744b-11e5-9376-f883c14ebabd.png)

Based from tagged version from this repository, version 0.1.3 is the latest.

**Comment by jocelyngirard** [comment]
+1

**Comment by KyleGoddard** [comment]
okay, I'll have a look asap.

**Comment by telip007** [comment]
same error here!

**Comment by telip007** [comment]
<img width="797" alt="bildschirmfoto 2015-10-25 um 19 53 10" src="https://cloud.githubusercontent.com/assets/8666886/10717257/1270ceea-7b52-11e5-8e2e-0e3d0a94efda.png">

Version is not updated :)

**Comment by telip007** [comment]
@KyleGoddard

**Comment by telip007** [comment]
solution: " pod 'KGFloatingDrawer', :git => 'https://github.com/KyleGoddard/KGFloatingDrawer.git' "

**Comment by KyleGoddard** [comment]
^ that works as a workaround. Sorry, cocoa pods is giving me some trouble, fix is incoming.

**Comment by KyleGoddard** [comment]
Okay sorry about that everyone, should be good now.

**Comment by mnbayan** [comment]
@KyleGoddard , Thanks it's working..
