### ISSUE TITLE
CodeSign Pod

### ISSUE THREAD

**Issue by sohil12** [KyleGoddard/KGFloatingDrawer#14]
If I let the default settings then it doesn't work, if I codesign pod with my Distribution profile, then due to build identifier it gives error, so I even created a separate provisioning profile but still facing errors. Please help

**Comment by KyleGoddard** [comment]
I'm afraid I don't understand. This sounds like a provisioning issue with your apple developer account?

**Comment by sohil12** [comment]
Hi,
I was able to solve that issue, I had to reintegrate the pod and codesign
it again with provisioning profiles. Thank you.

_Regards,_

http://www.corporatecoders.com

_Sohil Dedhia_

m: +91 844 669 2229

w: corporatecoders.com https://mail.google.com/

f: facebook.com/corporatecoders

**Comment by KyleGoddard** [comment]
Glad that it got sorted.
