### ISSUE TITLE
Error before download the KGFloatingDrawer "Expected type after as"

### ISSUE THREAD

**Issue by diegomaye** [KyleGoddard/KGFloatingDrawer#2]
Hi,

When I open the example project I found some errors related with instance unwrapped "!".  As I know the exclamation point is used for unwrap the instance, but I never see the "!" with the "as" like in KGDrawerView(line 215) 

``` scala
var view = self.centerViewContainer.subviews.first as! UIView
```

Sorry but I am new with swift and can't to figure out the problem, I try to delete the "!" unsuccessfully. I think that KGFloatingDrawer is an amazing component and I would like to use the examples to see the functionality.

![error](https://cloud.githubusercontent.com/assets/1084712/6889102/244e81bc-d665-11e4-96f4-7f764a9097f6.png)

Thanks in advance.

**Comment by KyleGoddard** [comment]
Can you verify that you are using XCode 6.3?

**Comment by KyleGoddard** [comment]
Closed as specific to Xcode 6.2 and Swift 1.1 which are unsupported.

**Comment by KyleGoddard** [comment]
You might be able to change the `as!` to just `as` or maybe `as?` and have it work with Swift 1.1 and Xcode 6.2 however it is likely that there are other parts of the library that will report hard errors for Swift 1.1 that are expected syntax in Swift 1.2.

**Comment by diegomaye** [comment]
Thanks Kyle
