### ISSUE TITLE
Menu not opening when pushing with segue

### ISSUE THREAD

**Issue by dprasse** [KyleGoddard/KGFloatingDrawer#22]
I'm trying to have 2 screens before my "Main" app. When I use get to my last screen which should be the menu screen, my button refuses to open the leftmenu. However, whenever I set the last screen as my center view, it works fine. Is there any way to use a segue and this repository at the same time? I'm trying to do a selection (school selection) before it goes into the actual main app. 

Thanks and great menu!

**Comment by KyleGoddard** [comment]
Can you provide a sample that illustrates this issue?
