### ISSUE TITLE
Xcode 8 - Swift 3

### ISSUE THREAD

**Issue by fred76** [KyleGoddard/KGFloatingDrawer#27]
Hi, sorry for the question, You will update the project to latest swift version

Thanks
Alberto

**Comment by swsalim** [comment]
I converted the code to swift 2.3, fixed any error messages and set up the views and storyboard based on the example.

I can see that the function applyTransforms is being called by when the toggleDrawer is trigger but it doesn't seem to do anything. The animation working and therefore I can't see the left drawer.

Any idea what I can check on this?

**Comment by KyleGoddard** [comment]
Finally getting around to this.
