### ISSUE TITLE
iPad not working

### ISSUE THREAD

**Issue by Urkman** [KyleGoddard/KGFloatingDrawer#3]
Not working in iPad

**Comment by KyleGoddard** [comment]
Can you elaborate on this? Aside from a graphical glitch in the hidden table view in the example project everything seems to work as expected. The graphical glitch can be corrected with the following code added to `LeftDrawerTableViewController.swift`:

```
    override func tableView(tableView: UITableView, willDisplayCell cell: UITableViewCell, forRowAtIndexPath indexPath: NSIndexPath) {
        cell.backgroundColor = UIColor.clearColor()
    }
```

I'll make sure to update the example project shortly.
