### ISSUE TITLE
No such module 'KGFloatingDrawer'

### ISSUE THREAD

**Issue by ghost** [KyleGoddard/KGFloatingDrawer#5]
When I open the Example Project I get this error "No such module KGFloatingDrawer"
I didn't understand the trouble...

**Comment by KyleGoddard** [comment]
Are you opening the Workspace or the Project?

**Comment by EdoardoLincetto** [comment]
Thanks Kyle another information is it possible to add the swipe gesture to open and close the menu?

**Comment by KyleGoddard** [comment]
Eduardo would you mind closing this and reopening it as a separate issue. These two questions are unrelated.

**Comment by KyleGoddard** [comment]
You could if you like copy the sources out of the pods directory and into the main project, but using the cocoa pod installation is way easier.
